[package]
name = "visual-id"
version = "0.1.0"
authors = ["Tom Godkin <tomgodkin@pm.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
png = "0.16"
bytes = "0.5"
